# Generated by Django 5.1.1 on 2024-09-22 09:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('stop_location', models.CharField(blank=True, max_length=255, null=True)),
                ('transportation_mode', models.CharField(choices=[('public', 'Public'), ('bike', 'Bike'), ('car', 'Car'), ('train', 'Train'), ('bus', 'Bus'), ('aeroplane', 'Aeroplane')], max_length=20)),
                ('service_type', models.CharField(blank=True, choices=[('ride', 'Ride'), ('delivery', 'Delivery')], max_length=20, null=True)),
                ('departure_time', models.DateTimeField()),
                ('ticket_image', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('is_live', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'FREE'), ('basic', 'BASIC'), ('rover', 'ROVER'), ('courier', 'COURIER'), ('courier_plus', 'COURIER PLUS')], default='free', max_length=100)),
                ('price', models.DecimalField(choices=[(Decimal('0'), '#0.00'), (Decimal('1200'), '#1,200'), (Decimal('4500'), '#4,500'), (Decimal('9400'), '#9,400'), (Decimal('15200'), '#15,200')], decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('duration', models.IntegerField(default=30, help_text='Duration in days')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returning', models.BooleanField(default=False)),
                ('returning_time', models.DateTimeField(blank=True, null=True)),
                ('is_repeated', models.BooleanField(default=False)),
                ('days_of_week', models.ManyToManyField(blank=True, to='Api.day')),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_route', to='Api.route')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=25, null=True)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photo/')),
                ('driver_license', models.ImageField(blank=True, null=True, upload_to='driver_license/')),
                ('vehicle_inspector_report', models.ImageField(blank=True, null=True, upload_to='vehicle_inspector_report/')),
                ('vehicle_insurance', models.ImageField(blank=True, null=True, upload_to='vehicle_insurance/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, unique=True)),
                ('instagram', models.URLField(blank=True, null=True, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50)),
                ('account_details', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('nin', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
