# Generated by Django 5.1.1 on 2024-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='driver_license',
            field=models.ImageField(blank=True, null=True, upload_to='driver_license/'),
        ),
    ]
