# Generated by Django 5.1.1 on 2025-08-03 06:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_badge_packageoffer_is_cancelled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('dva', 'Direct Virtual Account'), ('standard', 'Standard Account')], default='dva', max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paystack Account',
                'verbose_name_plural': 'Paystack Accounts',
            },
        ),
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('narration', models.CharField(blank=True, max_length=255, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paystack Transaction',
                'verbose_name_plural': 'Paystack Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
