# Generated by Django 5.1.1 on 2025-08-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0008_paystackaccount_paystacktransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paystackaccount",
            name="user",
        ),
        migrations.RemoveField(
            model_name="paystacktransaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="user",
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the notification",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Content/message of the notification"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the notification was created"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who receives the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.DeleteModel(
            name="PaystackAccount",
        ),
        migrations.DeleteModel(
            name="PaystackTransaction",
        ),
        migrations.DeleteModel(
            name="Transfer",
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
        migrations.DeleteModel(
            name="WithdrawalRequest",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="Api_notific_user_id_1dde2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_read", "-created_at"], name="Api_notific_is_read_a66977_idx"
            ),
        ),
    ]
