# Generated by Django 5.1.1 on 2025-12-03 16:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_badge_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ('name',), 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-created_at',), 'verbose_name': 'Bid', 'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-date_joined',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('name',), 'verbose_name': 'Day', 'verbose_name_plural': 'Days'},
        ),
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ('-created_at',), 'verbose_name': 'KYC', 'verbose_name_plural': 'KYC Records'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ('-created_at',), 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-created_at',), 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='packageoffer',
            options={'ordering': ('-created_at',), 'verbose_name': 'Package Offer', 'verbose_name_plural': 'Package Offers'},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ('-created_at',), 'verbose_name': 'QR Code', 'verbose_name_plural': 'QR Codes'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ('-created_at',), 'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterModelOptions(
            name='referraltoken',
            options={'ordering': ('-created_at',), 'verbose_name': 'Referral Token', 'verbose_name_plural': 'Referral Tokens'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('-created_at',), 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='scheduledroute',
            options={'ordering': ('-created_at',), 'verbose_name': 'Scheduled Route', 'verbose_name_plural': 'Scheduled Routes'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ('-created_at',), 'verbose_name': 'Social Media Link', 'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-created_at',), 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ('-created_at',), 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ('-awarded_at',), 'verbose_name': 'User Badge', 'verbose_name_plural': 'User Badges'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('-created_at',), 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
