# Generated by Django 5.1.1 on 2026-01-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_badge_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
