# Generated by Django 5.1.1 on 2026-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('user', 'code')},
        ),
    ]
