# Generated by Django 5.1.1 on 2026-01-02 20:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Bank name', max_length=100)),
                ('code', models.CharField(help_text='Bank code (e.g., NUBAN code)', max_length=10)),
                ('slug', models.CharField(blank=True, help_text='Paystack slug for the bank', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the bank is currently active/available')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When the bank was added', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the bank was last updated', null=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='wallet_bank_name_f60005_idx'), models.Index(fields=['code'], name='wallet_bank_code_e5c9d0_idx'), models.Index(fields=['is_active'], name='wallet_bank_is_acti_99b337_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('refund', 'Refund')], help_text='Type of transaction', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='External reference', max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', help_text='Transaction status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the transaction was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the transaction was last updated', null=True)),
                ('user', models.ForeignKey(help_text='User who performed the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallet_tran_user_id_46afdf_idx'), models.Index(fields=['transaction_type', 'status'], name='wallet_tran_transac_019d56_idx'), models.Index(fields=['reference'], name='wallet_tran_referen_f4b8af_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dva_account_number', models.CharField(blank=True, help_text='Dedicated Virtual Account number', max_length=20, null=True, unique=True)),
                ('dva_account_name', models.CharField(blank=True, help_text='Name on the DVA account', max_length=200, null=True)),
                ('dva_bank_name', models.CharField(blank=True, help_text='Bank name for the DVA', max_length=100, null=True)),
                ('dva_account_reference', models.CharField(blank=True, help_text='Reference on the DVA account', max_length=200, null=True)),
                ('dva_assigned_at', models.DateTimeField(blank=True, help_text='When the DVA was assigned', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the wallet was last updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the wallet was created', null=True)),
                ('user', models.OneToOneField(help_text='User account associated with this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='wallet_wall_user_id_03e396_idx'), models.Index(fields=['balance'], name='wallet_wall_balance_1ea64d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(help_text='Bank name for the withdrawal', max_length=100)),
                ('account_number', models.CharField(help_text='Bank account number for the withdrawal', max_length=20)),
                ('account_name', models.CharField(blank=True, help_text='Account name (verified by Paystack)', max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Withdrawal amount', max_digits=12, validators=[django.core.validators.MinValueValidator(100.0)])),
                ('transfer_reference', models.CharField(blank=True, help_text='Unique reference for Paystack transfer', max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Withdrawal status', max_length=10)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure (if any)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the withdrawal was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the withdrawal was last updated', null=True)),
                ('user', models.ForeignKey(help_text='User requesting the withdrawal', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallet_with_user_id_1a2d32_idx'), models.Index(fields=['status'], name='wallet_with_status_e9e494_idx'), models.Index(fields=['bank_name'], name='wallet_with_bank_na_c57af5_idx')],
            },
        ),
    ]
