# Generated by Django 5.1.1 on 2025-08-19 11:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bank name", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Bank code (e.g., NUBAN code)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        help_text="Paystack slug for the bank",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the bank is currently active/available",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the bank was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the bank was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank",
                "verbose_name_plural": "Banks",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="wallet_bank_name_f60005_idx"),
                    models.Index(fields=["code"], name="wallet_bank_code_e5c9d0_idx"),
                    models.Index(
                        fields=["is_active"], name="wallet_bank_is_acti_99b337_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("transfer", "Transfer"),
                            ("refund", "Refund"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference (e.g., Paystack)",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        help_text="Transaction status",
                        max_length=10,
                    ),
                ),
                (
                    "paystack_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Paystack transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the transaction was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the transaction was last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="wallet_tran_user_id_46afdf_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "status"],
                        name="wallet_tran_transac_019d56_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="wallet_tran_referen_f4b8af_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current wallet balance",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "paystack_customer_code",
                    models.CharField(
                        blank=True,
                        help_text="Paystack customer code for this user",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "dva_account_number",
                    models.CharField(
                        blank=True,
                        help_text="Dedicated Virtual Account number",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "dva_account_name",
                    models.CharField(
                        blank=True,
                        help_text="Name on the DVA account",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "dva_bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank name for the DVA",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "dva_assigned_at",
                    models.DateTimeField(
                        blank=True, help_text="When the DVA was assigned", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the wallet was last updated"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the wallet was created"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account associated with this wallet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="wallet_wall_user_id_03e396_idx"
                    ),
                    models.Index(
                        fields=["balance"], name="wallet_wall_balance_1ea64d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        help_text="Bank name for the withdrawal", max_length=100
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Bank account number for the withdrawal",
                        max_length=20,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        help_text="Account name (verified by Paystack)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Withdrawal amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(100.0)],
                    ),
                ),
                (
                    "paystack_recipient_code",
                    models.CharField(
                        blank=True,
                        help_text="Paystack Transfer Recipient Code",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "paystack_transfer_reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for Paystack transfer",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "paystack_transfer_id",
                    models.CharField(
                        blank=True,
                        help_text="Paystack internal Transfer ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Withdrawal status",
                        max_length=10,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="Reason for failure (if any)", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the withdrawal was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the withdrawal was last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting the withdrawal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal",
                "verbose_name_plural": "Withdrawals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="wallet_with_user_id_1a2d32_idx",
                    ),
                    models.Index(
                        fields=["status"], name="wallet_with_status_e9e494_idx"
                    ),
                    models.Index(
                        fields=["bank_name"], name="wallet_with_bank_na_c57af5_idx"
                    ),
                ],
            },
        ),
    ]
