# Generated by Django 5.1.1 on 2025-08-04 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0003_bank_alter_withdrawal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Withdrawal', 'verbose_name_plural': 'Withdrawals'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the bank was added'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(help_text='Bank code (e.g., NUBAN code)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the bank is currently active/available'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(help_text='Bank name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='slug',
            field=models.CharField(blank=True, help_text='Paystack slug for the bank', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the bank was last updated'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the transaction was created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, help_text='Paystack transaction ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, help_text='External reference (e.g., Paystack)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', help_text='Transaction status', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('refund', 'Refund')], help_text='Type of transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the transaction was last updated'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(help_text='User who performed the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the wallet was created'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='dva_account_name',
            field=models.CharField(blank=True, help_text='Name on the DVA account', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='dva_account_number',
            field=models.CharField(blank=True, help_text='Dedicated Virtual Account number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='dva_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the DVA was assigned', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='dva_bank_name',
            field=models.CharField(blank=True, help_text='Bank name for the DVA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='paystack_customer_code',
            field=models.CharField(blank=True, help_text='Paystack customer code for this user', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the wallet was last updated'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account name (verified by Paystack)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(help_text='Bank account number for the withdrawal', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Withdrawal amount', max_digits=12, validators=[django.core.validators.MinValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(help_text='Bank name for the withdrawal', max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the withdrawal was created'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for failure (if any)', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='paystack_transfer_id',
            field=models.CharField(blank=True, help_text='Paystack internal Transfer ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Withdrawal status', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the withdrawal was last updated'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(help_text='User requesting the withdrawal', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['name'], name='wallet_app__name_ffbdef_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['code'], name='wallet_app__code_672507_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['is_active'], name='wallet_app__is_acti_521f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='wallet_app__user_id_b69f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='wallet_app__transac_14893d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='wallet_app__referen_3773e4_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallet_app__user_id_ad7fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['balance'], name='wallet_app__balance_1f2b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', '-created_at'], name='wallet_app__user_id_3fa236_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='wallet_app__status_8f9590_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['bank_name'], name='wallet_app__bank_na_2559ee_idx'),
        ),
    ]
