# Generated by Django 5.1.1 on 2025-10-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0004_alter_bank_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(help_text='Bank name', max_length=100),
        ),
    ]
