# Generated by Django 5.1.1 on 2025-10-12 12:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0005_alter_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='paystack_transfer_reference',
            new_name='transfer_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paystack_transaction_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='paystack_customer_code',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='paystack_recipient_code',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='paystack_transfer_id',
        ),
        migrations.AddField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='dva_account_reference',
            field=models.CharField(blank=True, help_text='Reference on the DVA account', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the bank was added', null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(help_text='Bank code (e.g., NUBAN code)', max_length=10),
        ),
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the bank was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the transaction was created', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, help_text='External reference', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', help_text='Transaction status', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the transaction was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the wallet was created', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the wallet was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the withdrawal was created', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the withdrawal was last updated', null=True),
        ),
    ]
